language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nersesyan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t nersesyan/multi-client ./client
  - docker build -t nersesyan/multi-nginx ./nginx
  - docker build -t nersesyan/multi-server ./server
  - docker build -t nersesyan/multi-worker ./worker